name: Build and test on develop branch

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Android Build
      uses: vgaidarji/android-github-actions-build@v1.0.1
    - run: gradle -v
    - run: ./gradlew test
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build SampleApplication
      run: ./gradlew --no-daemon build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Gradle Build
      uses: gradle/gradle-build-action@v2.0.1
      with:
        gradle-version: 7.0.2
        cache-disabled: false
        cache-read-only: false
        arguments: |
                    test --debug --stacktrace --warning-mode=all
                    
    - run: ./gradlew test
